# -*- coding: utf-8 -*-
"""Assestment 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XCTvH0ENJKUtDcqWU2HWX3AA3Bgofk0U
"""

# =========================================
# Assignment 1: HDI Statistical Interpretation and EDA
# Student: [Your Name]
# =========================================

# -------------------------
# Import Libraries
# -------------------------
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
pd.set_option('display.max_columns', None)
sns.set(style='whitegrid')

# -------------------------
# Upload CSV (Colab-friendly)
# -------------------------
from google.colab import files
uploaded = files.upload()  # Select your CSV file

csv_file = list(uploaded.keys())[0]

# -------------------------
# Load Dataset with proper encoding
# -------------------------
try:
    hdi_df = pd.read_csv(csv_file, encoding='utf-8')
except UnicodeDecodeError:
    hdi_df = pd.read_csv(csv_file, encoding='latin1')  # fallback for Windows/Excel CSVs

print("Dataset Loaded!")
print(hdi_df.head())
print("\nColumns:", hdi_df.columns)

# -------------------------
# Ensure correct column names
# -------------------------
hdi_df.columns = [col.strip().lower().replace(" ", "_") for col in hdi_df.columns]

# Convert numeric columns
numeric_cols = ['year', 'hdi', 'life_expectancy', 'gross_inc_percap', 'education', 'gender_development']
for col in numeric_cols:
    if col in hdi_df.columns:
        hdi_df[col] = pd.to_numeric(hdi_df[col].replace(',', '', regex=True), errors='coerce')

# -------------------------
# Problem 1A: Single Year HDI Exploration (2022)
# -------------------------
hdi_2022_df = hdi_df[hdi_df['year'] == 2022].copy()
hdi_2022_df.drop_duplicates(inplace=True)

# Basic stats
print("HDI 2022 shape:", hdi_2022_df.shape)
print("Missing values:\n", hdi_2022_df.isnull().sum())

mean_hdi = hdi_2022_df['hdi'].mean()
median_hdi = hdi_2022_df['hdi'].median()
std_hdi = hdi_2022_df['hdi'].std()
print(f"HDI Mean: {mean_hdi:.3f}, Median: {median_hdi:.3f}, Std: {std_hdi:.3f}")

# Highest and lowest HDI countries
if 'hdi' in hdi_2022_df.columns:
    max_hdi_country = hdi_2022_df.loc[hdi_2022_df['hdi'].idxmax(), 'country']
    min_hdi_country = hdi_2022_df.loc[hdi_2022_df['hdi'].idxmin(), 'country']
    print("Highest HDI:", max_hdi_country)
    print("Lowest HDI:", min_hdi_country)

# HDI category
def hdi_category(hdi):
    if hdi < 0.550: return 'Low'
    elif hdi < 0.700: return 'Medium'
    elif hdi < 0.800: return 'High'
    else: return 'Very High'

hdi_2022_df['hdi_category'] = hdi_2022_df['hdi'].apply(hdi_category)
hdi_2022_df.to_csv('HDI_category_added.csv', index=False)

# Top HDI countries with GNI
if 'gross_inc_percap' in hdi_2022_df.columns:
    high_hdi_df = hdi_2022_df[hdi_2022_df['hdi'] > 0.800].sort_values('gross_inc_percap', ascending=False)
    print("Top 10 high HDI countries by GNI:\n", high_hdi_df[['country','hdi','gross_inc_percap']].head(10))

# -------------------------
# Problem 1B: HDI Trend Analysis (2020-2022)
# -------------------------
hdi_2020_2022_df = hdi_df[hdi_df['year'].isin([2020, 2021, 2022])].copy()
hdi_2020_2022_df.drop_duplicates(inplace=True)

# Line chart for example countries
countries = ['Nepal','India','Bangladesh','Bhutan','Sri Lanka']
plt.figure(figsize=(10,6))
for country in countries:
    subset = hdi_2020_2022_df[hdi_2020_2022_df['country'] == country].dropna(subset=['hdi'])
    plt.plot(subset['year'], subset['hdi'], marker='o', label=country)
plt.title('HDI Trend (2020-2022)')
plt.xlabel('Year')
plt.ylabel('HDI')
plt.legend()
plt.show()

# Average HDI by Region (bar chart)
if 'region' in hdi_2020_2022_df.columns:
    region_avg = hdi_2020_2022_df.groupby(['region','year'])['hdi'].mean().reset_index()
    plt.figure(figsize=(10,6))
    sns.barplot(x='region', y='hdi', hue='year', data=region_avg)
    plt.xticks(rotation=45)
    plt.title('Average HDI by Region (2020-2022)')
    plt.show()

# Box plot HDI distribution
plt.figure(figsize=(8,6))
sns.boxplot(x='year', y='hdi', data=hdi_2020_2022_df)
plt.title('HDI Distribution (2020-2022)')
plt.show()

# Scatter: HDI vs GNI
if 'gross_inc_percap' in hdi_2020_2022_df.columns:
    plt.figure(figsize=(8,6))
    sns.scatterplot(x='gross_inc_percap', y='hdi', data=hdi_2020_2022_df)
    plt.title('HDI vs GNI per Capita')
    plt.show()

# -------------------------
# Problem 2: South Asia Analysis
# -------------------------
south_asia = ["Afghanistan", "Bangladesh", "Bhutan", "India",
              "Maldives", "Nepal", "Pakistan", "Sri Lanka"]
hdi_southasia = hdi_df[hdi_df['country'].isin(south_asia)].copy()
hdi_southasia.to_csv('HDI_SouthAsia.csv', index=False)

# Composite Score (using life expectancy & GNI)
for col in ['life_expectancy','gross_inc_percap']:
    hdi_southasia[col] = pd.to_numeric(hdi_southasia[col], errors='coerce')
hdi_southasia['composite_score'] = 0.3*hdi_southasia['life_expectancy'] + 0.3*hdi_southasia['gross_inc_percap']

# Top 5 composite score plot
top5 = hdi_southasia.sort_values('composite_score', ascending=False).head(5)
plt.figure(figsize=(8,5))
sns.barplot(x='composite_score', y='country', data=top5)
plt.title('Top 5 South Asian Countries by Composite Score')
plt.show()

# Outliers using 1.5*IQR
Q1 = hdi_southasia['hdi'].quantile(0.25)
Q3 = hdi_southasia['hdi'].quantile(0.75)
IQR = Q3 - Q1
outliers = hdi_southasia[(hdi_southasia['hdi'] < Q1-1.5*IQR) | (hdi_southasia['hdi'] > Q3+1.5*IQR)]
print("Outliers:\n", outliers[['country','hdi']])

# Correlation
for m in ['life_expectancy','gender_development']:
    if m in hdi_southasia.columns:
        corr = hdi_southasia[m].corr(hdi_southasia['hdi'])
        print(f"Pearson correlation of {m} with HDI: {corr:.2f}")

# GNI-HDI Gap
hdi_southasia['gni_hdi_gap'] = hdi_southasia['gross_inc_percap'] - hdi_southasia['hdi']
print("Top 3 GNI-HDI gaps:\n", hdi_southasia.sort_values('gni_hdi_gap', ascending=False).head(3)[['country','gni_hdi_gap']])
print("Bottom 3 GNI-HDI gaps:\n", hdi_southasia.sort_values('gni_hdi_gap').head(3)[['country','gni_hdi_gap']])

# -------------------------
# Problem 3: South Asia vs Middle East
# -------------------------
middle_east = ["Bahrain", "Iran", "Iraq", "Israel", "Jordan",
               "Kuwait", "Lebanon", "Oman", "Palestine", "Qatar",
               "Saudi Arabia", "Syria", "United Arab Emirates", "Yemen"]

hdi_middleeast = hdi_2020_2022_df[hdi_2020_2022_df['country'].isin(middle_east)].copy()
hdi_southasia_2020_2022 = hdi_2020_2022_df[hdi_2020_2022_df['country'].isin(south_asia)].copy()

# Descriptive statistics
print("South Asia HDI mean/std:\n", hdi_southasia_2020_2022['hdi'].agg(['mean','std']))
print("Middle East HDI mean/std:\n", hdi_middleeast['hdi'].agg(['mean','std']))

# Top/Bottom performers
def top_bottom(df, region_name):
    top3 = df.sort_values('hdi', ascending=False).head(3)
    bottom3 = df.sort_values('hdi').head(3)
    print(f"{region_name} Top 3:\n", top3[['country','hdi']])
    print(f"{region_name} Bottom 3:\n", bottom3[['country','hdi']])
top_bottom(hdi_southasia_2020_2022, "South Asia")
top_bottom(hdi_middleeast, "Middle East")

# HDI Disparity
for region, df in zip(['South Asia','Middle East'], [hdi_southasia_2020_2022, hdi_middleeast]):
    hdi_range = df['hdi'].max(skipna=True) - df['hdi'].min(skipna=True)
    cv = df['hdi'].std(skipna=True)/df['hdi'].mean(skipna=True)
    print(f"{region} HDI range: {hdi_range:.2f}, Coefficient of Variation: {cv:.2f}")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!mkdir Assestment-1-AI
# %cd Assestment-1-AI
!git init